---
title: "HTML output that has embeded LaTeX tables and htmlwidget"
author: "Jonathan Sidi"
date: "January 31, 2017"
output: 
  html_document:
    self_contained: no
---

```{r setup, echo=FALSE,results='asis'}
suppressMessages(library(texPreview))
suppressMessages(library(slickR))
suppressMessages(library(xtable))

rt <- knitr::opts_knit$get('rmarkdown.pandoc.to')
tex_opts$set(list('returnType'= rt,'imgFormat'='svg'))

fd <- NULL 

if(rt%in%c("html", "html5", "s5", "slidy","slideous", "dzslides", "revealjs","md")){
  fd="testCarousel_files/texPreview"
  if(!dir.exists(fd)) dir.create(fd,recursive = TRUE)
  
}


```

## Table 1

```{r testOut, cache=FALSE, echo=TRUE, results='asis'}

      texPreview( obj = knitr::kable(mtcars,'latex'),
                  stem="testOut",
                  fileDir = fd,
                  opts.html = list(width='70%',height='70%')
                  
             )

```

## Table 2

```{r testOut2, cache=FALSE, echo=TRUE, results='asis'}

tab='
\\begin{tabular}{llr}
\\hline
\\multicolumn{2}{c}{Item} \\\\
\\cline{1-2}
Animal    & Description & Price (\\$) \\\\
\\hline
Gnat      & per gram    & 13.65      \\\\
          & each        & 0.01       \\\\
Gnu       & stuffed     & 92.50      \\\\
Emu       & stuffed     & 33.33      \\\\
Armadillo & frozen      & 8.99       \\\\
\\hline
\\end{tabular}'

      texPreview( obj = tab,
                  stem="testOut2",
                  fileDir = fd,
                  opts.html = list(width='40%',height='50%')
                  )
```

## Carousel (slickR htmlwidget)

```{r testOut3, cache=FALSE, echo=FALSE, results='asis'}
slickR::slickR(list.files(file.path(getwd(),fd),pattern = tex_opts$get('imgFormat'),full.names = TRUE))
```