---
title: "Using texPreview to create Carousels in Rmarkdown"
author: "Jonathan Sidi"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{texPreview Carousels}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.keep = "all",
  out.width = '75%',
  dev = c("png", "svg")
)
```

```{r}
library(texPreview)
library(slickR)
```

```{r}

objpath <- file.path(getwd(),"slickr_files/figure-html")

if(!dir.exists(objpath))
  dir.create(objpath,recursive = TRUE)

tex_opts$set(
  fileDir    = objpath, # path to save output
  returnType = 'html', # return images ready for html 
  imgFormat  = 'png' # return png images
  )
```

The first two chunks create outputs to place in the carousel in the last chunk.

## Kable Input

```{r kable}

knitr::kable(mtcars,'latex')%>%
  texPreview::tex_preview(stem = 'kable-1')

```

## TeX Input

```{r tex}

tab='
\\begin{tabular}{llr}
\\hline
\\multicolumn{2}{c}{Item} \\\\
\\cline{1-2}
Animal    & Description & Price (\\$) \\\\
\\hline
Gnat      & per gram    & 13.65      \\\\
          & each        & 0.01       \\\\
Gnu       & stuffed     & 92.50      \\\\
Emu       & stuffed     & 33.33      \\\\
Armadillo & frozen      & 8.99       \\\\
\\hline
\\end{tabular}'

tab%>%
  texPreview::tex_preview(stem = 'tex-1')
```

## Carousel

The images created above are placed in a [slickR](https://github.com/metrumresearchgroup/slickr) carousel.

```{r testOut3}

  slickR::slickR(
    list.files(objpath,full.names = TRUE,pattern = 'png'),
    height = 200,
    width = '95%')

```