---
title: "Using texPreview to create Tikz Outputs"
author: "Jonathan Sidi"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{texPreview Tikz}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

```{r}
library(texPreview)

tex_opts$set(
  returnType = knitr::opts_knit$get('rmarkdown.pandoc.to'),
  resizebox = FALSE  
)

```


```{r}

tikzEx   <- readLines(system.file('examples/tikz/credit-rationing.tex',package = 'texPreview'))
usetikz  <- paste(tikzEx[14:23],collapse="\n")
bodytikz <- paste(tikzEx[25:90],collapse="\n")
```

```{r}
texPreview::texPreview(
  obj = bodytikz,
  usrPackages = texPreview::build_usepackage(
    pkg = 'tikz',
    uselibrary = usetikz)
)

```

```{r}
useLib  <- "\\usetikzlibrary{arrows,shapes,snakes,automata,backgrounds,arrows.meta,positioning}"
useLib1 <- "\\usetikzlibrary{arrows,shapes,arrows.meta,positioning}"

texCode <- list( 
  g1 = list(
    
    bodyTikz = paste(readLines(system.file('examples/pkpdTikz/TwoCompartment.tex',package = 'texPreview')),
                     collapse='\n'),
    pkgs     = paste(build_usepackage(pkg = list('tikz'),uselibrary = useLib),
                     collapse='\n')),
  
  g2=list(
    bodyTikz = paste(readLines(system.file('examples/pkpdTikz/pdModel.tex',package = 'texPreview')),
                     collapse='\n'),
    pkgs     = paste(build_usepackage(pkg = list('tikz'),uselibrary = useLib1),
                     collapse='\n')),
  
  g3=list(
    bodyTikz = paste(readLines(system.file('examples/pkpdTikz/pkModel.tex',package = 'texPreview')),
                     collapse='\n'),
    pkgs     = paste(build_usepackage(pkg = list('tikz'),uselibrary = useLib1),
                     collapse='\n'))
  
  )
```

```{r}
texPreview::texPreview(obj = texCode$g1$bodyTikz,usrPackages = texCode$g1$pkgs)
```


```{r}
mymargins       <- tex_opts$get('margin')
mymargins$right <- 20

texPreview::texPreview(obj = texCode$g2$bodyTikz,
                       usrPackages = texCode$g2$pkgs,
                       margin = mymargins)
```


```{r}
texPreview::texPreview(obj = texCode$g3$bodyTikz,usrPackages = texCode$g3$pkgs)
```