---
title: "HTML output that has embeded LaTeX tables and htmlwidget"
author: "Jonathan Sidi"
date: "January 31, 2017"
output: html_document
---

```{r setup, echo=FALSE,results='asis'}
suppressMessages(library(texPreview))
suppressMessages(library(slickR))
suppressMessages(library(xtable))

tex_opts$set(list('returnType'= knitr::opts_knit$get('rmarkdown.pandoc.to'),'imgFormat'='svg'))

```

## Table 1

```{r testOut}

texPreview( obj = knitr::kable(mtcars,'latex'))

```

## Table 2

```{r testOut2}

tab='
\\begin{tabular}{llr}
\\hline
\\multicolumn{2}{c}{Item} \\\\
\\cline{1-2}
Animal    & Description & Price (\\$) \\\\
\\hline
Gnat      & per gram    & 13.65      \\\\
          & each        & 0.01       \\\\
Gnu       & stuffed     & 92.50      \\\\
Emu       & stuffed     & 33.33      \\\\
Armadillo & frozen      & 8.99       \\\\
\\hline
\\end{tabular}'

texPreview(obj = tab)
```

## Carousel (slickR htmlwidget)

```{r testOut3}
slickR::slickR(list.files(file.path(getwd(),"testCarousel_files/figure-html"),full.names = TRUE))
```