---
title: "ioslides output that has embeded LaTeX tables"
author: "Jonathan Sidi"
date: "January 31, 2017"
output: 
  ioslides_presentation:
    css: style.css
---

```{r setup, echo=FALSE,results='asis'}
suppressMessages(library(texPreview))

rt=knitr::opts_knit$get('rmarkdown.pandoc.to')
fd=NULL 

if(rt%in%c("html", "html5", "s5", "slidy","slideous", "dzslides", "revealjs","md")){
  fd="test_files/texPreview"
  if(!dir.exists(fd)) dir.create(fd,recursive = T)
  
   if(rt%in%c('html')){
     writeLines('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>')
     writeLines('<script src="zoomImage.js"></script>')
   }
}


```

# Slides

## Slide 1

```{r testOut, cache=FALSE, echo=FALSE, results='asis'}

      texPreview( obj = xtable(head(iris,20)),
                  stem="testOut",
                  fileDir = fd,
                  returnType=rt,
                  imgFormat = 'png',
                  opts.html = list(width='70%',height='70%')
                  
             )

```

## Slide 2

```{r testOut2, cache=FALSE, echo=FALSE, results='asis'}

tab='
\\begin{tabular}{llr}
\\hline
\\multicolumn{2}{c}{Item} \\\\
\\cline{1-2}
Animal    & Description & Price (\\$) \\\\
\\hline
Gnat      & per gram    & 13.65      \\\\
          & each        & 0.01       \\\\
Gnu       & stuffed     & 92.50      \\\\
Emu       & stuffed     & 33.33      \\\\
Armadillo & frozen      & 8.99       \\\\
\\hline
\\end{tabular}'

      texPreview( obj = tab,
                  stem="testOut2",
                  fileDir = fd,imgFormat = 'svg',
                  returnType=rt,opts.html = list(width='40%',height='50%')
                  )
```